import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SessionProviderWrapper from "@/components/SessionProvider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/SideMenuComponents/app-sidebar";
import GetSessionData from "@/components/auth";
import SignIn from "./auth/signin/page";
import Navbar from "@/components/Navbar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await GetSessionData();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <SessionProviderWrapper>
      {session ? (
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <Navbar />
            <div className="flex flex-1 flex-col gap-4 p-4 bg-gray-200 pt-[92px]">
              {children}
            </div>
          </SidebarInset>
        </SidebarProvider>
      ) : (
        <SignIn />
      )}
        </SessionProviderWrapper>  
      </body>
    </html>
  );
}
